Python 3.6.8 (default, Oct  7 2019, 12:59:55) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
======================= RESTART: /home/alunos/uber.py =======================
corridas no dia 50
valores das corridas: 300
Traceback (most recent call last):
  File "/home/alunos/uber.py", line 7, in <module>
    programa()
  File "/home/alunos/uber.py", line 5, in programa
    for i in corridas_dias(valor_da_corrida):
TypeError: 'int' object is not callable
>>> 
======================= RESTART: /home/alunos/uber.py =======================
corridas no dia10
valores das corridas: 30
Traceback (most recent call last):
  File "/home/alunos/uber.py", line 13, in <module>
    programa()
  File "/home/alunos/uber.py", line 6, in programa
    for i in corridas_dias:
TypeError: 'int' object is not iterable
>>> 
======================= RESTART: /home/alunos/uber.py =======================
corridas no dia10
valores das corridas: 20
Traceback (most recent call last):
  File "/home/alunos/uber.py", line 13, in <module>
    programa()
  File "/home/alunos/uber.py", line 6, in programa
    for i in corridas_dias:
TypeError: 'float' object is not iterable
>>> 
======================= RESTART: /home/alunos/uber.py =======================
corridas no dia30
valores das corridas: 20
Traceback (most recent call last):
  File "/home/alunos/uber.py", line 13, in <module>
    programa()
  File "/home/alunos/uber.py", line 6, in programa
    for i in corridas_dias:
TypeError: 'int' object is not iterable
>>> 
======================= RESTART: /home/alunos/uber.py =======================
corridas no dia2
valores das corridas: 10
Traceback (most recent call last):
  File "/home/alunos/uber.py", line 13, in <module>
    programa()
  File "/home/alunos/uber.py", line 6, in programa
    for valor_da_corrida in corridas_dias:
TypeError: 'int' object is not iterable
>>> 
======================= RESTART: /home/alunos/uber.py =======================
corridas no dia2
valores das corridas: 10
Traceback (most recent call last):
  File "/home/alunos/uber.py", line 13, in <module>
    programa()
  File "/home/alunos/uber.py", line 6, in programa
    for i in corridas_dias:
TypeError: 'int' object is not iterable
>>> 
======================= RESTART: /home/alunos/uber.py =======================
corridas no dia2
valores das corridas: 20
Traceback (most recent call last):
  File "/home/alunos/uber.py", line 13, in <module>
    programa()
  File "/home/alunos/uber.py", line 6, in programa
    for i in corridas:
TypeError: 'int' object is not iterable
>>> 
======================= RESTART: /home/alunos/uber.py =======================
corridas no dia2
valores das corridas: 10
Traceback (most recent call last):
  File "/home/alunos/uber.py", line 13, in <module>
    programa()
  File "/home/alunos/uber.py", line 6, in programa
    for i in corridas:
TypeError: 'int' object is not iterable
>>> 
======================= RESTART: /home/alunos/uber.py =======================
corridas no dia: 2
valores das corridas: 10
Traceback (most recent call last):
  File "/home/alunos/uber.py", line 13, in <module>
    programa()
  File "/home/alunos/uber.py", line 6, in programa
    for i in corridas:
TypeError: 'int' object is not iterable
>>> 
======================= RESTART: /home/alunos/uber.py =======================
corridas no dia: 2
valores das corridas: 10
Traceback (most recent call last):
  File "/home/alunos/uber.py", line 13, in <module>
    programa()
  File "/home/alunos/uber.py", line 6, in programa
    for i in corridas:
TypeError: 'int' object is not iterable
>>> 
======================= RESTART: /home/alunos/uber.py =======================
corridas no dia: 2
valores das corridas: 10
2.5
Traceback (most recent call last):
  File "/home/alunos/uber.py", line 13, in <module>
    programa()
  File "/home/alunos/uber.py", line 12, in programa
    print(aplitcativo)
NameError: name 'aplitcativo' is not defined
>>> 
======================= RESTART: /home/alunos/uber.py =======================
corridas no dia: 2
valores das corridas: 10
2.5
Traceback (most recent call last):
  File "/home/alunos/uber.py", line 13, in <module>
    programa()
  File "/home/alunos/uber.py", line 12, in programa
    print(aplitcativo)
NameError: name 'aplitcativo' is not defined
>>> 
======================= RESTART: /home/alunos/uber.py =======================
corridas no dia: 2
valores das corridas: 10
>>> 
======================= RESTART: /home/alunos/uber.py =======================
corridas no dia: 2
valores das corridas: 10
0
1
>>> 
======================= RESTART: /home/alunos/uber.py =======================
corridas no dia: 5
Traceback (most recent call last):
  File "/home/alunos/uber.py", line 14, in <module>
    programa()
  File "/home/alunos/uber.py", line 4, in programa
    uber = valor_da_corrida * 25/100
UnboundLocalError: local variable 'valor_da_corrida' referenced before assignment
>>> 
======================= RESTART: /home/alunos/uber.py =======================
corridas no dia: 3
Traceback (most recent call last):
  File "/home/alunos/uber.py", line 18, in <module>
    programa()
  File "/home/alunos/uber.py", line 4, in programa
    uber = valor_da_corrida * 25/100
UnboundLocalError: local variable 'valor_da_corrida' referenced before assignment
>>> 
======================= RESTART: /home/alunos/uber.py =======================
corridas no dia: 3
valores das corridas: 20
Traceback (most recent call last):
  File "/home/alunos/uber.py", line 16, in <module>
    programa()
  File "/home/alunos/uber.py", line 7, in programa
    uber = valor_total * 25/100
TypeError: unsupported operand type(s) for *: 'function' and 'int'
>>> 
======================= RESTART: /home/alunos/uber.py =======================
corridas no dia: 2
valores das corridas: 10
Traceback (most recent call last):
  File "/home/alunos/uber.py", line 13, in <module>
    programa()
  File "/home/alunos/uber.py", line 9, in programa
    uber = valor_total * 25/100
NameError: name 'valor_total' is not defined
>>> 
======================= RESTART: /home/alunos/uber.py =======================
corridas no dia: 3
valores das corridas: 10
2.5
valores das corridas: 15
4.0
valores das corridas: 30
8.0
>>> 
======================= RESTART: /home/alunos/uber.py =======================
corridas no dia: 2
valores das corridas: 10
valor do uber 2.5
valores do aplicativo 7.5
somar 10
valores das corridas: 15
valor do uber 4.0
valores do aplicativo 12.0
somar 16
>>> 
====================== RESTART: /home/alunos/futebol.py ======================
quantas o time jogou: 2
Traceback (most recent call last):
  File "/home/alunos/futebol.py", line 11, in <module>
    programa()
  File "/home/alunos/futebol.py", line 6, in programa
    for i in partidas():
TypeError: 'int' object is not callable
>>> 
====================== RESTART: /home/alunos/futebol.py ======================
quantas o time jogou: 2
resultado da partida: v
resultado da partida: v
>>> 
====================== RESTART: /home/alunos/futebol.py ======================
quantas o time jogou: 2
resultado da partida: v
6
resultado da partida: v
6
>>> 
====================== RESTART: /home/alunos/futebol.py ======================
quantas o time jogou: 5
resultado da partida: v
15 pontos
5 pontos
resultado da partida: 
====================== RESTART: /home/alunos/futebol.py ======================
quantas o time jogou: 5
resultado da partida: v
8 pontos
6 pontos
resultado da partida: v
8 pontos
6 pontos
resultado da partida: v
8 pontos
6 pontos
resultado da partida: f
8 pontos
6 pontos
resultado da partida: f
8 pontos
6 pontos
>>> 
====================== RESTART: /home/alunos/futebol.py ======================
quantas o time jogou: 
====================== RESTART: /home/alunos/futebol.py ======================
quantas o time jogou: 3
resultado da partida: v
0
6 pontos
4 pontos
resultado da partida: v
1
6 pontos
4 pontos
resultado da partida: v
2
6 pontos
4 pontos
>>> 
====================== RESTART: /home/alunos/futebol.py ======================
quantas o time jogou: 3
resultado da partida: v
0
vitoria 6 pontos
empate 4 pontos
resultado da partida: v
1
vitoria 6 pontos
empate 4 pontos
resultado da partida: f
2
vitoria 6 pontos
empate 4 pontos
>>> 
====================== RESTART: /home/alunos/futebol.py ======================
quantas o time jogou: 3
resultado da partida: v
0
Traceback (most recent call last):
  File "/home/alunos/futebol.py", line 15, in <module>
    programa()
  File "/home/alunos/futebol.py", line 9, in programa
    vitoria = partidas + len(v)
TypeError: object of type 'int' has no len()
>>> 
====================== RESTART: /home/alunos/futebol.py ======================
quantas o time jogou: 3
resultado da partida: v
vitoria 9 pontos
empate 3 pontos
vitoria 9 pontos
empate 3 pontos
vitoria 9 pontos
empate 3 pontos
resultado da partida: 
====================== RESTART: /home/alunos/futebol.py ======================
quantas o time jogou: 2
resultado da partida: v
resultado da partida: f
>>> 
====================== RESTART: /home/alunos/futebol.py ======================
quantas o time jogou: 3
resultado da partida: v
vitoria 9 pontos
empate 3 pontos
resultado da partida: e
vitoria 9 pontos
empate 3 pontos
resultado da partida: 
====================== RESTART: /home/alunos/futebol.py ======================
quantas o time jogou: 3
resultado da partida: v
vitoria 9 pontos
empate 3 pontos
resultado da partida: e
vitoria 9 pontos
empate 3 pontos
resultado da partida: 
====================== RESTART: /home/alunos/futebol.py ======================
quantas o time jogou: 3
resultado da partida: v
resultado da partida: f
resultado da partida: e
vitoria 9 pontos
empate 3 pontos
>>> 
======================= RESTART: /home/alunos/frase.py =======================
digite uma frase: vasco da gama
Traceback (most recent call last):
  File "/home/alunos/frase.py", line 20, in <module>
    programa()
  File "/home/alunos/frase.py", line 5, in programa
    if not eh_letra(c):
NameError: name 'c' is not defined
>>> 
======================= RESTART: /home/alunos/frase.py =======================
digite uma frase: felipe portela
Traceback (most recent call last):
  File "/home/alunos/frase.py", line 20, in <module>
    programa()
  File "/home/alunos/frase.py", line 5, in programa
    if not eh_letra():
  File "/home/alunos/frase.py", line 10, in eh_letra
    ord(90 < 127)
TypeError: ord() expected string of length 1, but bool found
>>> 
======================= RESTART: /home/alunos/frase.py =======================
digite uma frase: vasco da ma
Traceback (most recent call last):
  File "/home/alunos/frase.py", line 20, in <module>
    programa()
  File "/home/alunos/frase.py", line 5, in programa
    if not eh_letra():
  File "/home/alunos/frase.py", line 10, in eh_letra
    ord(90 < 127)
TypeError: ord() expected string of length 1, but bool found
>>> 
======================= RESTART: /home/alunos/frase.py =======================
digite uma frase: sso idf
Traceback (most recent call last):
  File "/home/alunos/frase.py", line 20, in <module>
    programa()
  File "/home/alunos/frase.py", line 5, in programa
    if not eh_letra():
  File "/home/alunos/frase.py", line 10, in eh_letra
    ord(frase)
NameError: name 'frase' is not defined
>>> 
======================= RESTART: /home/alunos/uber.py =======================
corridas no dia: 2
valores das corridas: 3
Traceback (most recent call last):
  File "/home/alunos/uber.py", line 17, in <module>
    programa()
  File "/home/alunos/uber.py", line 7, in programa
    if contador <  corridas:
NameError: name 'contador' is not defined
>>> 
======================= RESTART: /home/alunos/uber.py =======================
corridas no dia: 3
valores das corridas: 40
valor do uber 30.0
valores do aplicativo 90.0
somar 120
valores das corridas: 50
valor do uber 37.5
valores do aplicativo 112.5
somar 150
valores das corridas: 90
valor do uber 67.5
valores do aplicativo 202.5
somar 270
>>> 
